Repository libscie/ResearchEquals.com, pull requests merged in 2022-10, with the labels that each got.

#752 Match the breakpoint for showing the full nav bar tabs with the folding of the nav bar dropdown
  app/core/components/NavbarTabs.tsx
Labels: Stale

#726 Delete the duplicate supporting file query and use `invoke` instead
  app/modules/components/EditSupportingFiles.jsx
  app/modules/mutations/getSupportingFiles.ts
Labels: Maintenance, Stale

#755 Soft-code `pdfjs-dist`'s version number
  app/core/components/FilePreviewer.tsx
  blitz.config.ts
Labels: Stale

#733 Update the `faker` seeding script
  db/seeds.ts
Labels: Stale

#794 Prevent a "USER" account from publishing a collection
  app/core/modals/MakeCollectionPublicModal.tsx
  app/pages/collections/[suffix]/admin.tsx
Labels: Stale

#784 Fix Autocomplete's React 18 compatibility
  app/core/components/Autocomplete.tsx
Labels: Stale

#838 Add fix to citation_list
  app/core/crossref/citation_list.tsx
Labels: bug, Priority

#756 Make the "Got it!" text clickable in the email onboarding quest
  app/core/components/OnboardingQuests.jsx
Labels: visual design

#492 Introducing "Pay what you want"
  app/api/checkout_sessions.ts
  app/core/modals/PublishModuleModal.tsx
  app/core/styles/index.css
  app/modules/components/QuickDraft.tsx
  app/pages/index.tsx
  db/migrations/20221025085825_add_prod_id_to_license/migration.sql
  db/schema.prisma
  db/seeds.ts
Labels: enhancement, Priority

#861 Add admin reminting for collections
  app/collections/mutations/updateCrossRefCollection.ts
  app/core/queries/getAdminInfo.ts
  app/pages/admin.tsx
Labels: qa

#746 Add a confirmation modal when removing a supplementary file (& add an abstracted modal component)
  app/core/components/EditSupportingFileDisplay.tsx
  app/core/modals/Modal.tsx
Labels: enhancement

#876 Improve layering of collections confirmation modal
  app/core/modals/PayCreateCollectionModal.tsx
Labels: Priority
