Repository libscie/ResearchEquals.com, pull requests merged in 2022-08, with the labels that each got.

#551 Add algolia updatedAt indexing
  app/api/update-index.ts
  app/auth/mutations/verify-email.ts
Labels: enhancement

#559 Add FilePreviewer to drafts
  app/core/components/FilePreviewer.tsx
  app/modules/components/EditMainFile.jsx
  app/pages/modules/[suffix].tsx
Labels: enhancement

#553 Update the README and env files to more accurately reflect the setup process.
  .env.example
  .gitignore
  README.md
  app/auth/mutations/forgotPassword.test.ts
  docker-compose.yml
Labels: Stale

#556 Remove @stripe/stripe-js
  package-lock.json
  package.json
Labels: Stale

#573 Bump pdfjs-dist to 2.15.349
  app/core/components/FilePreviewer.tsx
  package-lock.json
  package.json
Labels: dependencies

#574 Improve text dropdown display
  app/modules/components/MetadataEdit.tsx
  app/modules/components/QuickDraft.tsx
Labels: visual design

#578 Add enum for ISO 639-1 language codes
  app/modules/components/MetadataEdit.tsx
  app/modules/components/QuickDraft.tsx
Labels: Stale

#577 Add broadcast for `SUPERADMIN`
  app/core/components/NavbarFullwidthMenu.tsx
  app/core/mutations/broadcast-message.ts
  app/pages/admin.tsx
  package-lock.json
  package.json
Labels: enhancement

#527 Add `/api/avatars/[handle]` route
  app/api/avatars/[handle].ts
  app/core/components/HandleAvatar.jsx
  db/seeds.ts
Labels: enhancement

#651 Add collections announcer
  app/core/components/NavbarDropdown.tsx
  app/core/components/NavbarFullwidthMenu.tsx
  app/core/components/NavbarTabs.tsx
  app/core/modals/CollectionsModal.tsx
  app/core/utils/Atoms.tsx
  app/pages/index.tsx
Labels: enhancement
